---
title: digitalRead()
categories: [ "Functions" ]
subCategories: [ "Digital I/O" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄

// PAGE TITLE
= digitalRead()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Lee el valor de un pin digital especificado, ya sea `HIGH` o` LOW`.


[float]
=== Sintaxis
`digitalRead(pin)`


[float]
=== Parámetros
`pin`: Número del pin digital a leer.

[float]
=== Retorno
`HIGH` o `LOW`.

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de ejemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Establece el pin 13 con el mismo valor que el pin 7, declarado como una entrada.

[%hardbreaks]
// CODE
[source,arduino]
----
int ledPin = 13;   // LED connected to digital pin 13
int inPin = 7;     // pushbutton connected to digital pin 7
int val = 0;       // variable to store the read value

void setup()
{
  pinMode(ledPin, OUTPUT);      // sets the digital pin 13 as output
  pinMode(inPin, INPUT);        // sets the digital pin 7 as input
}

void loop()
{
  val = digitalRead(inPin);     // read the input pin
  digitalWrite(ledPin, val);    // sets the LED to the button's value
}
----
[%hardbreaks]


[float]
=== Notas y advertencias
Si el pin no está conectado a nada, `digitalRead()` puede regresar `HIGH` o `LOW` (y esto puede cambiar aleatoriamente).

Los pines de entrada analógica se pueden usar como pines digitales, conocidos como A0, A1, etc.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver también

[role="example"]
* #Ejemplo# Tutorial: (http://arduino.cc/en/Tutorial/DigitalPins[Digital Pins])

--
// SEE ALSO SECTION ENDS
