---
title: digitalWrite()
categories: [ "Functions" ]
subCategories: [ "Digital I/O" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄

// PAGE TITLE
= digitalWrite()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Escribe un valor `HIGH` o `LOW` en un pin digital.

Si el pin se ha configurado como `OUTPUT` con `pinMode()`, su voltaje se establecerá en el valor correspondiente: `5` voltios (o `3,3` voltios en placas de `3,3` voltios) para `HIGH` y `0` voltios (ground) para `LOW`.

Si el pin se configura como `INPUT`, `digitalWrite()` habilitará (`ALTO`) o deshabilitará (`LOW`) el pullup interno en el pin de entrada. Se recomienda configurar `pinMode()` en `INPUT_PULLUP` para habilitar la resistencia interna de pull-up. Consulte el tutorial de pines digitales para obtener más información.

Si no configura el `pinMode()` en `OUTPUT`, y conecta un LED a un pin, al llamar `digitalWrite(HIGH)`, el LED puede aparecer atenuado. Sin establecer explícitamente `pinMode()`, `digitalWrite()` habrá habilitado la resistencia interna de pull-up, que actúa como una gran resistencia limitadora de corriente.


[float]
=== Sintaxis
`digitalWrite(pin, value)`


[float]
=== Parámetros
`pin`: Número de pin.

`value`: `HIGH` o `LOW`.


[float]
=== Retorna
Nada

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de ejemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
El código hace que el pin digital 13 sea `OUTPUT` y lo cambia alternando entre `HIGH` y `LOW` cada segundo.

[%hardbreaks]
// CODE
[source,arduino]
----
void setup()
{
  pinMode(13, OUTPUT);          // sets the digital pin 13 as output
}

void loop()
{
  digitalWrite(13, HIGH);       // sets the digital pin 13 on
  delay(1000);                  // waits for a second
  digitalWrite(13, LOW);        // sets the digital pin 13 off
  delay(1000);                  // waits for a second
}
----
[%hardbreaks]


[float]
=== Notas y advertencias
Los pines de entrada analógica se pueden usar como pines digitales, conocidos como A0, A1, etc.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver también

[role="example"]
* #Ejemplo# http://arduino.cc/en/Tutorial/DigitalPins[Tutorial: Digital Pins]

--
// SEE ALSO SECTION ENDS
