---
title: pinMode()
categories: [ "Functions" ]
subCategories: [ "Digital I/O" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄

// PAGE TITLE
= pinMode()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Configures the specified pin to behave either as an input or an output. See the description of (http://arduino.cc/en/Tutorial/DigitalPins[digital pins]) for details on the functionality of the pins.

A partir de Arduino 1.0.1, es posible habilitar las resistencias pullup internas con el modo INPUT_PULLUP. Además, el modo ENTRADA desactiva explícitamente el pullups interno.


[float]
=== Sintaxis
`pinMode(pin, mode)`


[float]
=== Parámetros
`pin`: Número del pin cuyo modo desea configurar.

`mode`: `INPUT`, `OUTPUT`, o `INPUT_PULLUP`. (consultar http://arduino.cc/en/Tutorial/DigitalPins[digital pins] para una descripción más completa de la funcionalidad.).


[float]
=== Retorno
Nada

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de ejemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
El código configura el pin digital 13 en `OUTPUT` luego alterna entre `HIGH` y `LOW`

[%hardbreaks]
// CODE
[source,arduino]
----
void setup()
{
  pinMode(13, OUTPUT);          // sets the digital pin 13 as output
}

void loop()
{
  digitalWrite(13, HIGH);       // sets the digital pin 13 on
  delay(1000);                  // waits for a second
  digitalWrite(13, LOW);        // sets the digital pin 13 off
  delay(1000);                  // waits for a second
}
----
[%hardbreaks]


[float]
=== Notas y advertencias
Los pines de entrada analógica se pueden usar como pines digitales, conocidos como A0, A1, etc.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver también

[role="example"]
* #Ejemplo# http://arduino.cc/en/Tutorial/DigitalPins[Description of the pins on an Arduino board]

--
// SEE ALSO SECTION ENDS
