---
title: analogWrite()
categories: [ "Functions" ]
subCategories: [ "Analog I/O" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄

// PAGE TITLE
= analogWrite()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Escribe un valor analógico (http://arduino.cc/en/Tutorial/PWM[PWM wave]) en un pin. Se puede usar para encender un LED con diferentes niveles de brillo o para conducir un motor a diferentes velocidades. Después de una llamada a `analogWrite()`, el pin generará una onda cuadrada constante del ciclo de trabajo especificado hasta la próxima llamada a `analogWrite()` (o una llamada a `digitalRead()` o `digitalWrite()`) en el mismo pin. La frecuencia de la señal `PWM` en la mayoría de los pines es de aproximadamente 490 Hz. En el Arduino Uno y placas similares, los pines 5 y 6 tienen una frecuencia de aproximadamente 980 Hz.

En la mayoría de las placas Arduino (con micocontroladores ATmega168 o ATmega328P), esta función trabaja en los pines 3, 5, 6, 9, 10 y 11. En el Arduino Mega, trabaja en los pines 2 - 13 y 44 - 46.

Las placas Arduino mas antiguas con un micocontrolador ATmega8 solo admiten `analogWrite()` en los pines 9, 10 y 11.

Arduino DUE admite `analogWrite()` en los pines 2 a 13, además de los pines DAC0 y DAC1. A diferencia de los pines PWM, DAC0 y DAC1 son convertidores digitales a analógicos y funcionan como salidas analógicas reales.

No necesita llamar `pinMode()` para establecer el pin como salida antes de llamar a `analogWrite()`.

La función `analogWrite()` no tiene nada que ver con los pines analógicos o la función `analogRead()`.


[float]
=== Sintaxis
`analogWrite(pin, value)`


[float]
=== Parámetros
`pin`: the pin to write to - `(int)`

`value`: Ciclo de trabajo: entre `0` (siempre apagado) y `255` (siempre encendido) - `(int)`


[float]
=== Retorno
Nada

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de ejemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Establece la salida del LED proporcional al valor leído en el potenciómetro.

[%hardbreaks]
// CODE
[source,arduino]
----
int ledPin = 9;      // LED connected to digital pin 9
int analogPin = 3;   // potentiometer connected to analog pin 3
int val = 0;         // variable to store the read value

void setup()
{
  pinMode(ledPin, OUTPUT);   // sets the pin as output
}

void loop()
{
  val = analogRead(analogPin);   // read the input pin
  analogWrite(ledPin, val / 4);  // analogRead values go from 0 to 1023, analogWrite values from 0 to 255
}
----
[%hardbreaks]


[float]
=== Notas y advertencias
Las salidas `PWM` generadas en los pines 5 y 6 tendrán ciclos de trabajo más altos de lo esperado. Esto se debe a las interacciones con las funciones `millis()` y `delay()`, que comparten el mismo temporizador interno utilizado para generar esas salidas `PWM`. Esto se notará principalmente en configuraciones de ciclo de trabajo bajo (por ejemplo, `0` a `10`) y puede dar como resultado un valor de cero (`0`) que no desactiva completamente la salida en los pines 5 y 6.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--


[float]
=== Ver también

[role="language"]
* #Lenguaje# link:../../zero-due-mkr-family/analogwriteresolution[analogWriteResolution()]

[role="definition"]
* #Definición# http://arduino.cc/en/Tutorial/PWM[PWM^]

[role="example"]
* #Ejemplo# http://arduino.cc/en/Tutorial/Blink[Blink^]

--
// SEE ALSO SECTION ENDS
