---
title: analogRead()
categories: [ "Functions" ]
subCategories: [ "Analog I/O" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄

// PAGE TITLE
= analogRead()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Lee el valor del pin analógico especificado. La placa Arduino contiene un convertidor analógico a digital de 6 canales (8 canales en Arduino Mini y Nano, 16 canales en Arduino Mega). Esto significa que mapeará voltajes de entrada entre `0` y `5` voltios en valores enteros entre `0` y `1023`. Esto produce una resolución entre las lecturas de: `5 voltios / 1024 unidades` o, 0.0049 voltios (4.9 mV) por unidad. El rango de entrada y la resolución se pueden cambiar usando link:../analogreference[`analogReference()`].

Se necesitan aproximadamente 100 microsegundos (0,0001 s) para leer una entrada analógica, por lo que la velocidad máxima de lectura es aproximadamente 10.000 veces por segundo.


[float]
=== Sintaxis
`analogRead(pin)`


[float]
=== Parámetros
`pin`: Pin de entrada analógica a leer (`0` a `5` en la mayoría de las placas, `0` a `7` en Arduino Mini y Nano, `0` a `15` en Arduino Mega) - `(int)`


[float]
=== Retorno
`int(0 a 1023)`

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de ejemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
El código lee el voltaje en `analogPin` y lo muestra.

[%hardbreaks]
// CODE
[source,arduino]
----
int analogPin = 3;     // potentiometer wiper (middle terminal) connected to analog pin 3
                       // outside leads to ground and +5V
int val = 0;           // variable to store the value read

void setup()
{
  Serial.begin(9600);              //  setup serial
}

void loop()
{
  val = analogRead(analogPin);     // read the input pin
  Serial.println(val);             // debug value
}
----
[%hardbreaks]


[float]
=== Notas y advertencias
Si el pin de entrada analógica no está conectado a nada, el valor devuelto por `analogRead()` fluctuará en función de una serie de factores (por ejemplo, los valores de las otras entradas analógicas, qué tan cerca está su mano de la placa, etc.).

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver también

[role="language"]
* #Lenguaje# link:../../zero-due-mkr-family/analogreadresolution[analogReadResolution()]
* #Lenguaje# https://www.arduino.cc/en/Tutorial/AnalogInputPins[Tutorial: Analog Input Pins]

--
// SEE ALSO SECTION ENDS
