---
title: interrupts()
categories: [ "Functions" ]
subCategories: [ "Interrupts" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄

// PAGE TITLE
= interrupts()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Reactiva las interrupciones (después de que hayan sido deshabilitados por link:../nointerrupts[nointerrupts()]). Las interrupciones permiten que ciertas tareas importantes sucedan en segundo plano y están habilitadas de manera predeterminada. Algunas funciones no funcionarán mientras las interrupciones estén deshabilitadas, y la comunicación entrante puede ignorarse. Sin embargo, las interrupciones pueden interrumpir levemente el tiempo del código y pueden deshabilitarse para secciones de código particularmente críticas.

[float]
=== Sintaxis
`interrupts()`


[float]
=== Parámetros
Nada.


[float]
=== Retorno
Nada.

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de ejemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
El código habilita `interrupts`.

[%hardbreaks]
// CODE
[source,arduino]
----
void setup() {

}

void loop()
{
  noInterrupts();
  // critical, time-sensitive code here
  interrupts();
  // other code here
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver también

[role="language"]
* #Lenguaje# link:../../external-interrupts/attachinterrupt[attachInterrupts()]
* #Lenguaje# link:../../external-interrupts/detachinterrupt[detachInterrupts()]

--
// SEE ALSO SECTION ENDS
