---
title: randomSeed()
categories: [ "Functions" ]
subCategories: [ "Random Numbers" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄

// PAGE TITLE
= randomSeed(seed)

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
`randomSeed()` inicializa el generador de números pseudoaleatorios, haciendo que comience en un punto arbitrario en su secuencia aleatoria. Esta secuencia, aunque es muy larga y aleatoria, siempre es la misma.

Si es importante que una secuencia de valores generados por `random()` difiera, en las ejecuciones posteriores de un sketch, use `randomSeed()` para inicializar el generador de números aleatorios con una entrada bastante aleatoria, como `analogRead()` en un pin desconectado.

Por el contrario, ocasionalmente puede ser útil usar secuencias pseudoaleatorias que se repiten exactamente. Esto se puede lograr llamando a `randomSeed()` con un número fijo, antes de comenzar la secuencia aleatoria.


[float]
=== Parameters
(`long` o `int`): pasa un número para generar la semilla.

[float]
=== Retorno
Nada

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de ejemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Salida por serial.

[source,arduino]
----
long randNumber;

void setup(){
  Serial.begin(9600);
  randomSeed(analogRead(0));
}

void loop(){
  randNumber = random(300);
  Serial.println(randNumber);

  delay(50);
}
----

--
// HOW TO USE SECTION ENDS
