---
title: random()
categories: [ "Functions" ]
subCategories: [ "Random Numbers" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄

// PAGE TITLE
= random()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
La función `random()` genera números pseudoaleatorios.


[float]
=== Sintaxis
`random(max)`

`random(min, max)`


[float]
=== Parámetros
`min`: límite inferior del valor aleatorio, inclusivo (opcional).

`max`: límite superior del valor aleatorio, exclusivo.


[float]
=== Returns
A random number between min and max-1 (`long`).

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de ejemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
El código genera números aleatorios y los muestra.

[%hardbreaks]
// CODE
[source,arduino]
----
long randNumber;

void setup(){
  Serial.begin(9600);

  // if analog input pin 0 is unconnected, random analog
  // noise will cause the call to randomSeed() to generate
  // different seed numbers each time the sketch runs.
  // randomSeed() will then shuffle the random function.
  randomSeed(analogRead(0));
}

void loop() {
  // print a random number from 0 to 299
  randNumber = random(300);
  Serial.println(randNumber);

  // print a random number from 10 to 19
  randNumber = random(10, 20);
  Serial.println(randNumber);

  delay(50);
}
----
[%hardbreaks]


[float]
=== Notas y advertencias
Si es importante que una secuencia de valores generados por `random()` difiera, en las ejecuciones posteriores de un sketch, use `randomSeed()` para inicializar el generador de números aleatorios con una entrada bastante aleatoria, como `analogRead()` en un pin desconectado.

Por el contrario, ocasionalmente puede ser útil usar secuencias pseudoaleatorias que se repiten exactamente. Esto se puede lograr llamando a `randomSeed()` con un número fijo, antes de comenzar la secuencia aleatoria.

--
// HOW TO USE SECTION ENDS
