---
title: pulseIn()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄

// PAGE TITLE
= pulseIn()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Lee un pulso (`HIGH` o `LOW`) en un pin. Por ejemplo, si `value` es `HIGH`, `pulseIn()` espera a que el pin sea `HIGH`, comienza a temporizar, luego espera a que el pin vaya a `LOW` y detiene el cronometraje. Devuelve la duración del pulso en microsegundos. Otorga y devuelve cero (`0`) si no se inicia ningún pulso dentro de un tiempo de espera especificado.

El tiempo de esta función se ha determinado empíricamente y probablemente muestre errores en pulsos largos. Funciona en pulsos de 10 microsegundos a 3 minutos de duración.


[float]
=== Sintaxis
`pulseIn(pin, value)`

`pulseIn(pin, value, timeout)`


[float]
=== Parámetros
`pin`: El número del pin en el que desea leer el pulso - `(int)`.

`value`: Tipo de pulso a leer: ya sea link:../../../variables/constants/constants/[`HIGH`] o link:../../../variables/constants/constants/[`LOW`] - `(int)`.

`timeout` (opcional): El número de microsegundos que esperará a que comience el pulso; el valor predeterminado es un segundo - `(unsigned long)`.


[float]
=== Retorno
la duración del pulso (en microsegundos) o cero (`0`) si no se inició el pulso antes del tiempo determinado (`timeout`) - `(unsigned long)`.

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de ejemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
El ejemplo calcula la duración de un pulso en el pin 7.
[%hardbreaks]
// CODE
[source,arduino]
----
int pin = 7;
unsigned long duration;

void setup()
{
  pinMode(pin, INPUT);
}

void loop()
{
  duration = pulseIn(pin, HIGH);
}
----

--
// HOW TO USE SECTION ENDS
