---
title: pulseInLong()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄

// PAGE TITLE
= pulseInLong()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Lee un pulso (`HIGH` o `LOW`) en un pin. Por ejemplo, si `value` es `HIGH`, `pulseInLong()` espera a que el pin sea `HIGH`, comienza a temporizar, luego espera a que el pin vaya a `LOW` y detiene el cronometraje. Devuelve la duración del pulso en microsegundos o cero (`0`) si no se recibe un pulso completo dentro del tiempo de espera.

El tiempo de esta función se ha determinado empíricamente y probablemente muestre errores en pulsos cortos. Funciona en pulsos de 10 microsegundos a 3 minutos de duración. Tenga en cuenta que si el pin ya está `HIGH` cuando se llama a la función, esta esperará a que el pin pase a `LOW` y luego a `HIGH` antes de comenzar a contar. Esta rutina puede usarse solo si las interrupciones están activadas. Además, la resolución más alta se obtiene con intervalos grandes.


[float]
=== Sintaxis
`pulseInLong(pin, value)`

`pulseInLong(pin, value, timeout)`


[float]
=== Parámetros
`pin`: El número del pin en el que desea leer el pulso - `(int)`.

`value`: Tipo de pulso a leer: ya sea link:../../../variables/constants/constants/[`HIGH`] o link:../../../variables/constants/constants/[`LOW`] - `(int)`.

`timeout` (opcional): El número de microsegundos que esperará a que comience el pulso; el valor predeterminado es un segundo - `(unsigned long)`.


[float]
=== Retorno
la duración del pulso (en microsegundos) o cero (`0`) si no se inició el pulso antes del tiempo determinado (`timeout`) - `(unsigned long)`.

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de ejemplo
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
El ejemplo calcula la duración de un pulso en el pin 7.
[%hardbreaks]
// CODE
[source,arduino]
----
int pin = 7;
unsigned long duration;

void setup() {
  pinMode(pin, INPUT);
}

void loop() {
  duration = pulseInLong(pin, HIGH);
}
----


[float]
=== Notas y advertencias
Esta función se basa en `micros()` por lo que no se puede usar en el contexto link:../../interrupts/nointerrupts[`noInterrupts()`].

--
// HOW TO USE SECTION ENDS
