---
title: shiftIn()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄

// PAGE TITLE
= shiftIn()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Cambia en un byte de datos, un bit por vez. Comienza desde el bit más significativo (es decir, el más a la izquierda) o menos significativo (el más a la derecha). Para cada bit, el pin del reloj pasa a nivel `HIGH`, el siguiente bit se lee de la línea de datos, y luego el pin del reloj pasa a nivel `LOW`.

Si está interactuando con un dispositivo que está marcado por bordes de subida, deberá asegurarse de que el pin del reloj esté bajo antes de la primera llamada a `shiftIn()`, con una llamada a `digitalWrite(clockPin, LOW)`.

Nota: esta es una implementación de software; Arduino también proporciona una link:https://www.arduino.cc/en/Reference/SPI[librería SPI] que usa la implementación de hardware, que es más rápida pero solo funciona en pines específicos.


[float]
=== Sintaxis
`byte incoming = shiftIn(dataPin, clockPin, bitOrder)`


[float]
=== Parámetros
`dataPin`: Pin en el que se ingresa cada bit - `(int)`

`clockPin`: Pin que cambia cuando se hace una lectura con `dataPin`

`bitOrder`: Orden en que se desplazan los bits de entrada; ya sea `MSBFIRST` o `LSBFIRST`. (Most Significant Bit First, Least Significant Bit First)


[float]
=== Retorno
el valor leído `(byte)`.

--
// OVERVIEW SECTION ENDS
