---
title: tone()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---
// ARDUINO LANGUAGE REFERENCE TAG (above)   ►►►►► ALWAYS INCLUDE IN YOUR FILE ◄◄◄◄◄

// PAGE TITLE
= tone()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
Genera una onda cuadrada de la frecuencia especificada (y un ciclo de trabajo del 50%) en un pin. Se puede especificar una duración, de lo contrario la onda continúa hasta que se realice una llamada a link:../noTone[`noTone()`]. El pin se puede conectar a un zumbador piezoeléctrico u otro altavoz para reproducir tonos.

Solo se puede generar un tono a la vez. Si ya se está reproduciendo un tono en un pin diferente, la llamada a `tone()` no tendrá efecto. Si el tono se reproduce en el mismo pin, la llamada establecerá su frecuencia.

El uso de la función `tone()` interferirá con la salida `PWM` en los pines 3 y 11 (en placas que no sean Mega).

No es posible generar tonos inferiores a 31Hz. Para detalles técnicos, ver https://github.com/bhagman/Tone#ugly-details[Brett Hagman's notes].


[float]
=== Sintaxis
`tone(pin, frequency)`

`tone(pin, frequency, duration)`


[float]
=== Parámetros
`pin`: Pin en el cual se desea generar el tono

`frequency`: Frecuencia del tono en hercios - `(unsigned int)`

`duration`: Duración del tono en milisegundos (opcional) - `(unsigned long)`


[float]
=== Retorno
Nada

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Notas y advertencias
Si desea reproducir tonos diferentes en varios pines, debe llamar a `noTone()` en un pin antes de llamar a `tone()` en el siguiente pin.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Ver también

[role="language"]
* #Lenguaje:# link:../../analog-io/analogwrite[analogWrite()]

[role="example"]
* #Ejemplo:# http://arduino.cc/en/Tutorial/Tone[Tone^]
* #Ejemplo:# http://arduino.cc/en/Tutorial/Tone[Pitch follower^]
* #Ejemplo:# http://arduino.cc/en/Tutorial/Tone3[Simple Keyboard^]
* #Ejemplo:# http://arduino.cc/en/Tutorial/Tone4[multiple tones^]
* #Ejemplo:# http://arduino.cc/en/Tutorial/PWM[PWM^]

--
// SEE ALSO SECTION ENDS
